# Generated by Django 5.0.6 on 2024-07-29 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_email', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='meetup',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='meetup',
            name='details',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.meetupdetails'),
        ),
    ]
