# Generated by Django 5.0.6 on 2024-07-29 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_meetupdetails_alter_meetup_slug_meetup_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetupdetails',
            old_name='organization_email',
            new_name='organizer_email',
        ),
        migrations.RenameField(
            model_name='meetupdetails',
            old_name='organization_name',
            new_name='organizer_name',
        ),
    ]
