# Generated by Django 5.0.6 on 2024-07-30 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_participant_meetup_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='participants',
        ),
        migrations.AddField(
            model_name='meetup',
            name='participants',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.participant'),
        ),
    ]
