# Generated by Django 5.0.6 on 2024-07-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_meetup_participants_meetup_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='participants',
        ),
        migrations.AddField(
            model_name='meetup',
            name='participants',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='homepage.participant'),
        ),
    ]
